apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html
data:
  index.html: | 
    <!DOCTYPE html>
    <html>
      <head><title>{{ .Values.page.title }}</title></head>
      <body>
        <h1>{{ .Values.page.body }}</h1>
        <img src="bild.jpeg">
        <p>Release: {{ .Release.Name }} / Namespace: {{ .Release.Namespace }}</p>
      </body>
    </html>
binaryData:
  bild.jpeg: {{ .Files.Get "files/bild.jpeg" | b64enc }}
