apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prefix }}
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: 80
          {{- if .Values.env }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html 
      volumes:
        - name: html
          configMap:
            name: {{ .Release.Name }}-html 

