apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.prefix }}
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}
    spec:
      containers:
        - name: web
          image: {{ .Values.image }}
          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
          

