# Sealed secret - helm install

- name: Sealed secret
  hosts: k3s_server
  become: true

  vars:
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml
    sealed_secrets_namespace: kube-system
    sealed_secrets_key: "{{ lookup('env', 'SEALED_SECRETS_KEY_B64', default=undef()) | b64decode }}"
    sealed_secrets_crt: "{{ lookup('env', 'SEALED_SECRETS_CRT_B64', default=undef()) | b64decode }}"

  tasks:
    - name: Python3 kubernetes validation
      ansible.builtin.apt:
        name: python3-kubernetes
        state: present
        update_cache: true

    - name: Sealing Key
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: sealed-secrets-key
            namespace: "{{ sealed_secrets_namespace }}"
            labels:
              sealedsecrets.bitnami.com/sealed-secrets-key: active
          type: kubernetes.io/tls
          stringData:
            tls.key: "{{ sealed_secrets_key }}"
            tls.crt: "{{ sealed_secrets_crt }}"
      no_log: true

    - name: Install Sealed Secrets
      kubernetes.core.helm:
        kubeconfig: "{{ kubeconfig_path }}"
        name: sealed-secrets
        chart_ref: sealed-secrets
        chart_repo_url: https://bitnami.github.io/sealed-secrets
        chart_version: 2.20.0
        release_namespace: "{{ sealed_secrets_namespace }}"
        wait: true
