apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.12.1
    helm:
      releaseName: alloy
      valuesObject:
        controller:
          type: deployment
          replicas: 1
        alloy:
          configMap:
            content: |
              discovery.kubernetes "pods" {
              role = "pod"
              }

              loki.source.kubernetes "pods" {
                targets    = discovery.kubernetes.pods.targets
                forward_to = [loki.write.default.receiver]
              }

              loki.write "default" {
                endpoint {
                  url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
                }
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
